name: TFGS

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Clone
      run: |
        git clone https://github.com/GTrees-N/AxolotlEditor-gui
    - name: Build
      run: |
        cd AxolotlEditor-gui
        npm install
        npm run build
        cd ..
    - name: Upload
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: scratch-gui/build
        target_branch: GTrees-N/AxolotlEditor-gui
        verbose: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

